import { Client, Project, Invoice, Proposal, Task, TimeEntry, Conversation, Message } from '@/types'

// ── Creative-focused mock data ──────────────────────────────────────────────
// Clients are record labels, galleries, event promoters, content agencies,
// and independent artists — the people creative freelancers actually work with.

export const mockClients: Client[] = [
  {
    id: 'client-1',
    name: 'Marcus Webb',
    email: 'marcus@nightowlrecords.com',
    phone: '+1 (323) 555-0147',
    company: 'Night Owl Records',
    address: '4420 Sunset Blvd, Los Angeles, CA 90027',
    notes: 'Indie label. 3-album deal for cover art + music videos. Net-30 terms.',
    createdAt: '2026-01-10',
    activeProjects: 3,
    totalBilled: 18500,
  },
  {
    id: 'client-2',
    name: 'Sonia Alvarez',
    email: 'sonia@luminagallery.com',
    phone: '+1 (212) 555-0293',
    company: 'Lumina Gallery',
    address: '88 Wooster St, New York, NY 10012',
    notes: 'Contemporary gallery. Needs website refresh + event photo coverage quarterly.',
    createdAt: '2026-02-05',
    activeProjects: 2,
    totalBilled: 12800,
  },
  {
    id: 'client-3',
    name: 'DJ Kael',
    email: 'kael@kaelmusic.com',
    phone: '+1 (305) 555-0412',
    company: null,
    address: '1200 Collins Ave, Miami Beach, FL 33139',
    notes: 'Independent artist. Needs branding, visualizers, and social content for EP launch.',
    createdAt: '2026-02-20',
    activeProjects: 2,
    totalBilled: 7200,
  },
  {
    id: 'client-4',
    name: 'Priya Nair',
    email: 'priya@baselineevents.com',
    phone: '+1 (512) 555-0188',
    company: 'Baseline Events',
    address: '305 E 6th St, Austin, TX 78701',
    notes: 'Event promoter. Monthly festival + club night flyers, photo/video coverage.',
    createdAt: '2026-01-25',
    activeProjects: 1,
    totalBilled: 9400,
  },
  {
    id: 'client-5',
    name: 'Tyler Osei',
    email: 'tyler@frameworkcreative.co',
    phone: '+1 (404) 555-0375',
    company: 'Framework Creative',
    address: '250 Spring St NW, Atlanta, GA 30303',
    notes: 'Creative agency. Subcontracts design work for their artist roster.',
    createdAt: '2026-03-01',
    activeProjects: 1,
    totalBilled: 4600,
  },
]

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    clientId: 'client-1',
    clientName: 'Night Owl Records',
    title: 'Album Cover Art — "Midnight Frequency"',
    description: 'Full album artwork package: cover, back, disc label, and 3 singles artwork for vinyl + digital release',
    status: 'active',
    startDate: '2026-04-01',
    endDate: '2026-05-15',
    budget: 4500,
    hoursLogged: 18,
    progress: 55,
    createdAt: '2026-03-25',
  },
  {
    id: 'proj-2',
    clientId: 'client-1',
    clientName: 'Night Owl Records',
    title: 'Music Video — Lead Single',
    description: 'Concept, shoot, and edit 3:30 music video for lead single. Includes color grading and VFX.',
    status: 'in_progress',
    startDate: '2026-04-10',
    endDate: '2026-06-01',
    budget: 8000,
    hoursLogged: 24,
    progress: 35,
    createdAt: '2026-03-28',
  },
  {
    id: 'proj-3',
    clientId: 'client-2',
    clientName: 'Lumina Gallery',
    title: 'Gallery Website Redesign',
    description: 'Modern portfolio site with artist pages, exhibition calendar, and online viewing rooms',
    status: 'in_progress',
    startDate: '2026-03-15',
    endDate: '2026-05-20',
    budget: 6500,
    hoursLogged: 32,
    progress: 68,
    createdAt: '2026-03-10',
  },
  {
    id: 'proj-4',
    clientId: 'client-2',
    clientName: 'Lumina Gallery',
    title: 'Spring Exhibition Photo Coverage',
    description: 'On-site event photography for spring opening — 150+ edited photos, same-night social selects',
    status: 'review',
    startDate: '2026-04-05',
    endDate: '2026-04-20',
    budget: 2200,
    hoursLogged: 10,
    progress: 90,
    createdAt: '2026-03-20',
  },
  {
    id: 'proj-5',
    clientId: 'client-3',
    clientName: 'DJ Kael',
    title: 'EP Visual Identity & Branding',
    description: 'Logo refresh, color palette, typography, and social media templates for upcoming EP',
    status: 'active',
    startDate: '2026-03-01',
    endDate: '2026-04-30',
    budget: 3200,
    hoursLogged: 16,
    progress: 70,
    createdAt: '2026-02-20',
  },
  {
    id: 'proj-6',
    clientId: 'client-3',
    clientName: 'DJ Kael',
    title: 'Audio Visualizer Pack',
    description: '5 looping audio-reactive visualizers for live sets and YouTube uploads',
    status: 'active',
    startDate: '2026-04-05',
    endDate: '2026-05-10',
    budget: 2800,
    hoursLogged: 8,
    progress: 30,
    createdAt: '2026-04-01',
  },
  {
    id: 'proj-7',
    clientId: 'client-4',
    clientName: 'Baseline Events',
    title: 'Summer Festival Promo Package',
    description: 'Flyer design, social media assets, artist lineup graphics, and event recap video',
    status: 'active',
    startDate: '2026-04-01',
    endDate: '2026-06-15',
    budget: 5500,
    hoursLogged: 12,
    progress: 25,
    createdAt: '2026-03-25',
  },
  {
    id: 'proj-8',
    clientId: 'client-5',
    clientName: 'Framework Creative',
    title: 'Artist Portfolio Websites (x3)',
    description: 'Template-based portfolio sites for 3 emerging artists on their roster',
    status: 'in_progress',
    startDate: '2026-04-05',
    endDate: '2026-05-30',
    budget: 4200,
    hoursLogged: 14,
    progress: 40,
    createdAt: '2026-03-30',
  },
  {
    id: 'proj-9',
    clientId: 'client-1',
    clientName: 'Night Owl Records',
    title: 'Merch Design — Tour Collection',
    description: 'T-shirt, hoodie, and poster designs for upcoming tour merch drop',
    status: 'completed',
    startDate: '2026-02-01',
    endDate: '2026-03-15',
    budget: 3000,
    hoursLogged: 20,
    progress: 100,
    createdAt: '2026-01-25',
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    clientId: 'client-1',
    clientName: 'Night Owl Records',
    projectId: 'proj-9',
    projectTitle: 'Merch Design — Tour Collection',
    invoiceNumber: 'INV-001',
    status: 'paid',
    lineItems: [
      { id: 'li-1', description: 'T-shirt designs (3 colorways)', quantity: 3, rate: 350, total: 1050 },
      { id: 'li-2', description: 'Hoodie design', quantity: 1, rate: 400, total: 400 },
      { id: 'li-3', description: 'Tour poster illustration', quantity: 1, rate: 550, total: 550 },
    ],
    subtotal: 2000,
    tax: 0,
    total: 2000,
    dueDate: '2026-03-30',
    paidAt: '2026-03-28',
    notes: 'Merch designs delivered. Print-ready files sent via Dropbox.',
    createdAt: '2026-03-15',
  },
  {
    id: 'inv-2',
    clientId: 'client-2',
    clientName: 'Lumina Gallery',
    projectId: 'proj-3',
    projectTitle: 'Gallery Website Redesign',
    invoiceNumber: 'INV-002',
    status: 'paid',
    lineItems: [
      { id: 'li-4', description: 'Website design — Phase 1 (wireframes + mockups)', quantity: 1, rate: 2500, total: 2500 },
      { id: 'li-5', description: 'Stock photography licensing', quantity: 1, rate: 180, total: 180 },
    ],
    subtotal: 2680,
    tax: 0,
    total: 2680,
    dueDate: '2026-04-10',
    paidAt: '2026-04-08',
    notes: '50% milestone — design phase complete.',
    createdAt: '2026-03-28',
  },
  {
    id: 'inv-3',
    clientId: 'client-3',
    clientName: 'DJ Kael',
    projectId: 'proj-5',
    projectTitle: 'EP Visual Identity & Branding',
    invoiceNumber: 'INV-003',
    status: 'sent',
    lineItems: [
      { id: 'li-6', description: 'Logo design + brand guide', quantity: 1, rate: 1800, total: 1800 },
      { id: 'li-7', description: 'Social media template kit (10 templates)', quantity: 10, rate: 75, total: 750 },
    ],
    subtotal: 2550,
    tax: 0,
    total: 2550,
    dueDate: '2026-05-01',
    notes: 'Final brand assets delivered. Awaiting payment.',
    createdAt: '2026-04-15',
  },
  {
    id: 'inv-4',
    clientId: 'client-4',
    clientName: 'Baseline Events',
    projectId: 'proj-7',
    projectTitle: 'Summer Festival Promo Package',
    invoiceNumber: 'INV-004',
    status: 'overdue',
    lineItems: [
      { id: 'li-8', description: 'Festival flyer design', quantity: 1, rate: 600, total: 600 },
      { id: 'li-9', description: 'Social media content pack (20 assets)', quantity: 20, rate: 85, total: 1700 },
      { id: 'li-10', description: 'Artist lineup graphic', quantity: 1, rate: 400, total: 400 },
    ],
    subtotal: 2700,
    tax: 0,
    total: 2700,
    dueDate: '2026-04-10',
    notes: 'Phase 1 deliverables — design assets. 15 days overdue.',
    createdAt: '2026-03-28',
  },
  {
    id: 'inv-5',
    clientId: 'client-1',
    clientName: 'Night Owl Records',
    projectId: 'proj-1',
    projectTitle: 'Album Cover Art — "Midnight Frequency"',
    invoiceNumber: 'INV-005',
    status: 'draft',
    lineItems: [
      { id: 'li-11', description: 'Album cover illustration', quantity: 1, rate: 1500, total: 1500 },
      { id: 'li-12', description: 'Back cover + disc label', quantity: 1, rate: 800, total: 800 },
      { id: 'li-13', description: 'Singles artwork (3)', quantity: 3, rate: 400, total: 1200 },
    ],
    subtotal: 3500,
    tax: 0,
    total: 3500,
    dueDate: '2026-05-30',
    notes: 'Draft — will send once final artwork is approved.',
    createdAt: '2026-04-20',
  },
  {
    id: 'inv-6',
    clientId: 'client-5',
    clientName: 'Framework Creative',
    projectId: 'proj-8',
    projectTitle: 'Artist Portfolio Websites (x3)',
    invoiceNumber: 'INV-006',
    status: 'sent',
    lineItems: [
      { id: 'li-14', description: 'Portfolio site build (per artist)', quantity: 3, rate: 1200, total: 3600 },
      { id: 'li-15', description: 'Domain + hosting setup', quantity: 3, rate: 50, total: 150 },
    ],
    subtotal: 3750,
    tax: 0,
    total: 3750,
    dueDate: '2026-05-15',
    notes: 'Net-15 per agency agreement.',
    createdAt: '2026-04-18',
  },
]

export const mockProposals: Proposal[] = [
  {
    id: 'prop-1',
    clientId: 'client-1',
    clientName: 'Night Owl Records',
    title: 'Full Visual Package — Fall Album Cycle',
    status: 'sent',
    lineItems: [
      { id: 'pli-1', description: 'Album artwork (cover + back + disc + 4 singles)', quantity: 1, rate: 4500, total: 4500 },
      { id: 'pli-2', description: 'Music video (concept through final edit)', quantity: 1, rate: 8000, total: 8000 },
      { id: 'pli-3', description: 'Lyric video', quantity: 1, rate: 2000, total: 2000 },
    ],
    total: 14500,
    intro: 'Complete visual identity for the fall album cycle — cover art, music video, and lyric video bundled at a package rate.',
    terms: '50% deposit to begin, 25% at rough cut, 25% on final delivery. Timeline: 8 weeks.',
    sentAt: '2026-04-12',
    createdAt: '2026-04-08',
  },
  {
    id: 'prop-2',
    clientId: 'client-4',
    clientName: 'Baseline Events',
    title: 'Year-Round Event Branding Retainer',
    status: 'draft',
    lineItems: [
      { id: 'pli-4', description: 'Monthly event flyer + social pack', quantity: 12, rate: 800, total: 9600 },
      { id: 'pli-5', description: 'Quarterly recap video (per event)', quantity: 4, rate: 1500, total: 6000 },
      { id: 'pli-6', description: 'Brand refresh (annual)', quantity: 1, rate: 2500, total: 2500 },
    ],
    total: 18100,
    intro: 'Annual retainer covering all design and video needs for your event calendar.',
    terms: 'Monthly retainer of $1,508.33. First and last month due upfront.',
    createdAt: '2026-04-05',
  },
  {
    id: 'prop-3',
    clientId: 'client-3',
    clientName: 'DJ Kael',
    title: 'Live Show Visual Package',
    status: 'accepted',
    lineItems: [
      { id: 'pli-7', description: 'Audio-reactive visualizer pack (5 loops)', quantity: 1, rate: 2800, total: 2800 },
      { id: 'pli-8', description: 'Stage backdrop design (print-ready)', quantity: 1, rate: 600, total: 600 },
    ],
    total: 3400,
    intro: 'Visual package for live DJ sets — reactive loops and branded stage presence.',
    terms: 'Full payment on delivery. Includes 2 revision rounds.',
    sentAt: '2026-03-15',
    createdAt: '2026-03-10',
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Sketch 3 album cover concepts',
    description: 'Create 3 distinct visual directions for "Midnight Frequency" album cover',
    status: 'done',
    dueDate: '2026-04-10',
    createdAt: '2026-04-01',
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Finalize selected cover art',
    description: 'Refine the approved concept into print-ready artwork (3000x3000 + vinyl dimensions)',
    status: 'in_progress',
    dueDate: '2026-05-01',
    createdAt: '2026-04-12',
  },
  {
    id: 'task-3',
    projectId: 'proj-2',
    title: 'Write treatment for music video',
    description: 'Concept treatment doc: mood, location, wardrobe, shot list, timeline',
    status: 'done',
    dueDate: '2026-04-15',
    createdAt: '2026-04-05',
  },
  {
    id: 'task-4',
    projectId: 'proj-2',
    title: 'Shoot day — music video',
    description: 'Full production day. Location: warehouse downtown. Call time 7am.',
    status: 'in_progress',
    dueDate: '2026-04-28',
    createdAt: '2026-04-10',
  },
  {
    id: 'task-5',
    projectId: 'proj-3',
    title: 'Build exhibition calendar component',
    description: 'Interactive calendar showing upcoming shows with artist filtering',
    status: 'in_progress',
    dueDate: '2026-04-25',
    createdAt: '2026-03-20',
  },
  {
    id: 'task-6',
    projectId: 'proj-4',
    title: 'Deliver edited selects from spring opening',
    description: 'Cull 800+ shots down to 150 edited, deliver via gallery link',
    status: 'in_progress',
    dueDate: '2026-04-18',
    createdAt: '2026-04-06',
  },
  {
    id: 'task-7',
    projectId: 'proj-5',
    title: 'Design social media template kit',
    description: '10 Canva/Figma templates: story, post, carousel, and event promo',
    status: 'todo',
    dueDate: '2026-04-28',
    createdAt: '2026-04-01',
  },
  {
    id: 'task-8',
    projectId: 'proj-6',
    title: 'Create first 2 visualizer loops',
    description: 'Audio-reactive loops in After Effects / TouchDesigner for live DJ set use',
    status: 'in_progress',
    dueDate: '2026-04-22',
    createdAt: '2026-04-08',
  },
  {
    id: 'task-9',
    projectId: 'proj-7',
    title: 'Design festival flyer',
    description: 'Main event flyer: 11x17 print + Instagram story + Facebook event cover',
    status: 'done',
    dueDate: '2026-04-12',
    createdAt: '2026-04-01',
  },
  {
    id: 'task-10',
    projectId: 'proj-8',
    title: 'Build first artist portfolio site',
    description: 'Set up template, customize for first artist, deploy to subdomain',
    status: 'in_progress',
    dueDate: '2026-04-20',
    createdAt: '2026-04-08',
  },
]

export const mockTimeEntries: TimeEntry[] = [
  {
    id: 'te-1',
    projectId: 'proj-1',
    projectTitle: 'Album Cover Art — "Midnight Frequency"',
    clientName: 'Night Owl Records',
    description: 'Initial concept sketches — 3 directions',
    hours: 4.5,
    hourlyRate: 85,
    date: '2026-04-08',
    createdAt: '2026-04-08',
  },
  {
    id: 'te-2',
    projectId: 'proj-1',
    projectTitle: 'Album Cover Art — "Midnight Frequency"',
    clientName: 'Night Owl Records',
    description: 'Refined selected concept + color exploration',
    hours: 3.5,
    hourlyRate: 85,
    date: '2026-04-10',
    createdAt: '2026-04-10',
  },
  {
    id: 'te-3',
    projectId: 'proj-2',
    projectTitle: 'Music Video — Lead Single',
    clientName: 'Night Owl Records',
    description: 'Treatment writing + shot list + location scouting',
    hours: 5,
    hourlyRate: 100,
    date: '2026-04-11',
    createdAt: '2026-04-11',
  },
  {
    id: 'te-4',
    projectId: 'proj-3',
    projectTitle: 'Gallery Website Redesign',
    clientName: 'Lumina Gallery',
    description: 'Homepage layout + artist page wireframes',
    hours: 6,
    hourlyRate: 95,
    date: '2026-04-09',
    createdAt: '2026-04-09',
  },
  {
    id: 'te-5',
    projectId: 'proj-3',
    projectTitle: 'Gallery Website Redesign',
    clientName: 'Lumina Gallery',
    description: 'Exhibition calendar component — frontend build',
    hours: 4,
    hourlyRate: 95,
    date: '2026-04-12',
    createdAt: '2026-04-12',
  },
  {
    id: 'te-6',
    projectId: 'proj-4',
    projectTitle: 'Spring Exhibition Photo Coverage',
    clientName: 'Lumina Gallery',
    description: 'On-site photography — spring opening night',
    hours: 4,
    hourlyRate: 125,
    date: '2026-04-06',
    createdAt: '2026-04-06',
  },
  {
    id: 'te-7',
    projectId: 'proj-4',
    projectTitle: 'Spring Exhibition Photo Coverage',
    clientName: 'Lumina Gallery',
    description: 'Photo culling + editing (batch 1)',
    hours: 3.5,
    hourlyRate: 80,
    date: '2026-04-08',
    createdAt: '2026-04-08',
  },
  {
    id: 'te-8',
    projectId: 'proj-5',
    projectTitle: 'EP Visual Identity & Branding',
    clientName: 'DJ Kael',
    description: 'Logo exploration — 5 directions',
    hours: 3,
    hourlyRate: 85,
    date: '2026-04-07',
    createdAt: '2026-04-07',
  },
  {
    id: 'te-9',
    projectId: 'proj-5',
    projectTitle: 'EP Visual Identity & Branding',
    clientName: 'DJ Kael',
    description: 'Brand guide — typography + palette + usage rules',
    hours: 4,
    hourlyRate: 85,
    date: '2026-04-10',
    createdAt: '2026-04-10',
  },
  {
    id: 'te-10',
    projectId: 'proj-6',
    projectTitle: 'Audio Visualizer Pack',
    clientName: 'DJ Kael',
    description: 'Visualizer loop #1 — waveform reactive',
    hours: 5,
    hourlyRate: 100,
    date: '2026-04-14',
    createdAt: '2026-04-14',
  },
  {
    id: 'te-11',
    projectId: 'proj-7',
    projectTitle: 'Summer Festival Promo Package',
    clientName: 'Baseline Events',
    description: 'Festival flyer design — concepts + final',
    hours: 4,
    hourlyRate: 90,
    date: '2026-04-05',
    createdAt: '2026-04-05',
  },
  {
    id: 'te-12',
    projectId: 'proj-7',
    projectTitle: 'Summer Festival Promo Package',
    clientName: 'Baseline Events',
    description: 'Social media content pack — first 10 assets',
    hours: 5.5,
    hourlyRate: 75,
    date: '2026-04-11',
    createdAt: '2026-04-11',
  },
  {
    id: 'te-13',
    projectId: 'proj-8',
    projectTitle: 'Artist Portfolio Websites (x3)',
    clientName: 'Framework Creative',
    description: 'Template setup + first artist customization',
    hours: 6,
    hourlyRate: 90,
    date: '2026-04-12',
    createdAt: '2026-04-12',
  },
  {
    id: 'te-14',
    projectId: 'proj-8',
    projectTitle: 'Artist Portfolio Websites (x3)',
    clientName: 'Framework Creative',
    description: 'Second artist site — content migration + styling',
    hours: 4.5,
    hourlyRate: 90,
    date: '2026-04-15',
    createdAt: '2026-04-15',
  },
  {
    id: 'te-15',
    projectId: 'proj-2',
    projectTitle: 'Music Video — Lead Single',
    clientName: 'Night Owl Records',
    description: 'Pre-production — storyboard + casting',
    hours: 3,
    hourlyRate: 100,
    date: '2026-04-16',
    createdAt: '2026-04-16',
  },
]

export const mockConversations: Conversation[] = [
  {
    clientId: 'client-1',
    clientName: 'Marcus Webb',
    clientCompany: 'Night Owl Records',
    lastMessage: 'Concept B is the vibe. Let\'s push that direction — can you have the refined version by Friday?',
    lastMessageAt: '2026-04-18T14:30:00Z',
    unreadCount: 1,
    messages: [
      {
        id: 'msg-1',
        clientId: 'client-1',
        sender: 'user',
        body: 'Hey Marcus — 3 album cover concepts attached. Let me know which direction resonates and I\'ll refine from there.',
        createdAt: '2026-04-17T10:00:00Z',
        readAt: '2026-04-17T10:05:00Z',
      },
      {
        id: 'msg-2',
        clientId: 'client-1',
        sender: 'client',
        body: 'These are fire. The artist loves Concept B — that darker palette with the neon accents. Can you push more contrast?',
        createdAt: '2026-04-17T15:30:00Z',
      },
      {
        id: 'msg-3',
        clientId: 'client-1',
        sender: 'user',
        body: 'Absolutely. I\'ll push the contrast and send a refined version. Also — should I start on the back cover once we lock this in?',
        createdAt: '2026-04-18T09:15:00Z',
        readAt: '2026-04-18T09:20:00Z',
      },
      {
        id: 'msg-4',
        clientId: 'client-1',
        sender: 'client',
        body: 'Concept B is the vibe. Let\'s push that direction — can you have the refined version by Friday?',
        createdAt: '2026-04-18T14:30:00Z',
      },
    ],
  },
  {
    clientId: 'client-3',
    clientName: 'DJ Kael',
    clientCompany: '',
    lastMessage: 'The visualizers look crazy in the set! Crowd was losing it. Gonna need 3 more for the festival run.',
    lastMessageAt: '2026-04-16T22:45:00Z',
    unreadCount: 2,
    messages: [
      {
        id: 'msg-5',
        clientId: 'client-3',
        sender: 'user',
        body: 'First 2 visualizer loops are ready — exported as 4K ProRes with alpha. Test them with your setup and let me know if the reactivity feels right.',
        createdAt: '2026-04-15T11:00:00Z',
        readAt: '2026-04-15T11:10:00Z',
      },
      {
        id: 'msg-6',
        clientId: 'client-3',
        sender: 'client',
        body: 'Bro these are insane. Tested them at the club last night.',
        createdAt: '2026-04-16T14:00:00Z',
      },
      {
        id: 'msg-7',
        clientId: 'client-3',
        sender: 'client',
        body: 'The visualizers look crazy in the set! Crowd was losing it. Gonna need 3 more for the festival run.',
        createdAt: '2026-04-16T22:45:00Z',
      },
    ],
  },
]
