import { Client, Project, Invoice, Proposal, Task, TimeEntry, Conversation, Message } from '@/types'

export const mockClients: Client[] = [
  {
    id: 'client-1',
    name: 'Alex Turner',
    email: 'alex@brightdigital.com',
    phone: '+1 (555) 123-4567',
    company: 'Bright Digital Co',
    address: '123 Innovation Blvd, San Francisco, CA 94102',
    notes: 'Long-term retainer client. Prefer monthly invoicing.',
    createdAt: '2024-01-15',
    activeProjects: 3,
    totalBilled: 42500,
  },
  {
    id: 'client-2',
    name: 'Maria Santos',
    email: 'maria@santosarch.com',
    phone: '+1 (555) 234-5678',
    company: 'Santos Architecture',
    address: '456 Design St, Austin, TX 78701',
    notes: 'Architecture firm. Projects typically $5k-10k.',
    createdAt: '2024-02-20',
    activeProjects: 2,
    totalBilled: 28900,
  },
  {
    id: 'client-3',
    name: 'James Park',
    email: 'james@velocitystartups.io',
    phone: '+1 (555) 345-6789',
    company: 'Velocity Startups',
    address: '789 Startup Ave, New York, NY 10001',
    notes: 'Early-stage startup. Fast-moving projects.',
    createdAt: '2024-03-10',
    activeProjects: 1,
    totalBilled: 15200,
  },
  {
    id: 'client-4',
    name: 'Emma Collins',
    email: 'emma@collinslaw.com',
    phone: '+1 (555) 456-7890',
    company: 'Collins & Co Law',
    address: '321 Legal Lane, Boston, MA 02108',
    notes: 'Law firm. Premium hourly rates negotiated.',
    createdAt: '2024-01-05',
    activeProjects: 0,
    totalBilled: 38600,
  },
  {
    id: 'client-5',
    name: 'David Reyes',
    email: 'david@reyescreative.com',
    phone: '+1 (555) 567-8901',
    company: 'Reyes Creative Agency',
    address: '654 Creative Dr, Los Angeles, CA 90001',
    notes: 'Creative agency. Multiple concurrent projects.',
    createdAt: '2024-02-01',
    activeProjects: 2,
    totalBilled: 8400,
  },
]

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    clientId: 'client-1',
    clientName: 'Bright Digital Co',
    title: 'Brand Identity Redesign',
    description: 'Complete rebrand including logo, color palette, and brand guidelines',
    status: 'active',
    startDate: '2024-04-01',
    endDate: '2024-05-15',
    budget: 8500,
    hoursLogged: 32,
    progress: 65,
    createdAt: '2024-03-25',
  },
  {
    id: 'proj-2',
    clientId: 'client-1',
    clientName: 'Bright Digital Co',
    title: 'Q2 Marketing Campaign',
    description: 'Social media content, email templates, and landing page design',
    status: 'in_progress',
    startDate: '2024-04-10',
    endDate: '2024-06-30',
    budget: 12000,
    hoursLogged: 48,
    progress: 45,
    createdAt: '2024-03-28',
  },
  {
    id: 'proj-3',
    clientId: 'client-2',
    clientName: 'Santos Architecture',
    title: 'Website Redesign',
    description: 'Modern, responsive website with portfolio showcase',
    status: 'in_progress',
    startDate: '2024-03-15',
    endDate: '2024-05-20',
    budget: 6500,
    hoursLogged: 28,
    progress: 72,
    createdAt: '2024-03-10',
  },
  {
    id: 'proj-4',
    clientId: 'client-2',
    clientName: 'Santos Architecture',
    title: 'Mobile App MVP',
    description: 'iOS/Android MVP for project collaboration tool',
    status: 'review',
    startDate: '2024-02-01',
    endDate: '2024-04-30',
    budget: 15000,
    hoursLogged: 92,
    progress: 90,
    createdAt: '2024-01-20',
  },
  {
    id: 'proj-5',
    clientId: 'client-3',
    clientName: 'Velocity Startups',
    title: 'Content Strategy & SEO',
    description: 'Blog content calendar and SEO optimization for 3 months',
    status: 'active',
    startDate: '2024-03-01',
    endDate: '2024-06-01',
    budget: 4200,
    hoursLogged: 18,
    progress: 35,
    createdAt: '2024-02-15',
  },
  {
    id: 'proj-6',
    clientId: 'client-5',
    clientName: 'Reyes Creative Agency',
    title: 'Email Template Suite',
    description: 'Responsive email templates for client campaigns',
    status: 'completed',
    startDate: '2024-01-10',
    endDate: '2024-02-28',
    budget: 3800,
    hoursLogged: 22,
    progress: 100,
    createdAt: '2024-01-05',
  },
  {
    id: 'proj-7',
    clientId: 'client-5',
    clientName: 'Reyes Creative Agency',
    title: 'Social Media Design Pack',
    description: 'Templates and assets for Instagram, Facebook, LinkedIn',
    status: 'completed',
    startDate: '2024-02-01',
    endDate: '2024-03-15',
    budget: 2800,
    hoursLogged: 16,
    progress: 100,
    createdAt: '2024-01-25',
  },
  {
    id: 'proj-8',
    clientId: 'client-1',
    clientName: 'Bright Digital Co',
    title: 'Analytics Dashboard',
    description: 'Custom analytics dashboard integration with GA4',
    status: 'active',
    startDate: '2024-04-05',
    endDate: '2024-05-30',
    budget: 5500,
    hoursLogged: 14,
    progress: 25,
    createdAt: '2024-03-30',
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    clientId: 'client-1',
    clientName: 'Bright Digital Co',
    projectId: 'proj-1',
    projectTitle: 'Brand Identity Redesign',
    invoiceNumber: 'INV-001',
    status: 'paid',
    lineItems: [
      { id: 'li-1', description: 'Design Hours (32h @ $85/hr)', quantity: 32, rate: 85, total: 2720 },
      { id: 'li-2', description: 'Revision & Approval', quantity: 1, rate: 480, total: 480 },
    ],
    subtotal: 3200,
    tax: 320,
    total: 3520,
    dueDate: '2024-04-15',
    paidAt: '2024-04-12',
    notes: 'Partial invoice for phase 1.',
    createdAt: '2024-04-01',
  },
  {
    id: 'inv-2',
    clientId: 'client-2',
    clientName: 'Santos Architecture',
    projectId: 'proj-3',
    projectTitle: 'Website Redesign',
    invoiceNumber: 'INV-002',
    status: 'paid',
    lineItems: [
      { id: 'li-3', description: 'Web Design & Development (28h @ $95/hr)', quantity: 28, rate: 95, total: 2660 },
      { id: 'li-4', description: 'Hosting Setup & Migration', quantity: 1, rate: 740, total: 740 },
    ],
    subtotal: 3400,
    tax: 340,
    total: 3740,
    dueDate: '2024-03-30',
    paidAt: '2024-03-28',
    notes: 'Invoice for completed design phase.',
    createdAt: '2024-03-15',
  },
  {
    id: 'inv-3',
    clientId: 'client-3',
    clientName: 'Velocity Startups',
    projectId: 'proj-5',
    projectTitle: 'Content Strategy & SEO',
    invoiceNumber: 'INV-003',
    status: 'sent',
    lineItems: [
      { id: 'li-5', description: 'Content Strategy Workshop', quantity: 1, rate: 1200, total: 1200 },
      { id: 'li-6', description: 'SEO Optimization (18h @ $75/hr)', quantity: 18, rate: 75, total: 1350 },
      { id: 'li-7', description: 'Initial Consulting', quantity: 1, rate: 250, total: 250 },
    ],
    subtotal: 2800,
    tax: 280,
    total: 3080,
    dueDate: '2024-04-30',
    notes: 'First month services.',
    createdAt: '2024-04-01',
  },
  {
    id: 'inv-4',
    clientId: 'client-5',
    clientName: 'Reyes Creative Agency',
    projectId: 'proj-6',
    projectTitle: 'Email Template Suite',
    invoiceNumber: 'INV-004',
    status: 'overdue',
    lineItems: [
      { id: 'li-8', description: 'Email Template Design (22h @ $90/hr)', quantity: 22, rate: 90, total: 1980 },
      { id: 'li-9', description: 'Testing & QA', quantity: 1, rate: 520, total: 520 },
    ],
    subtotal: 2500,
    tax: 250,
    total: 2750,
    dueDate: '2024-03-15',
    notes: 'Completed email templates invoice.',
    createdAt: '2024-02-28',
  },
  {
    id: 'inv-5',
    clientId: 'client-1',
    clientName: 'Bright Digital Co',
    projectId: 'proj-2',
    projectTitle: 'Q2 Marketing Campaign',
    invoiceNumber: 'INV-005',
    status: 'draft',
    lineItems: [
      { id: 'li-10', description: 'Campaign Strategy & Planning', quantity: 1, rate: 1500, total: 1500 },
    ],
    subtotal: 1500,
    tax: 150,
    total: 1650,
    dueDate: '2024-05-15',
    notes: 'Draft invoice for campaign planning phase.',
    createdAt: '2024-04-08',
  },
  {
    id: 'inv-6',
    clientId: 'client-2',
    clientName: 'Santos Architecture',
    projectId: 'proj-4',
    projectTitle: 'Mobile App MVP',
    invoiceNumber: 'INV-006',
    status: 'sent',
    lineItems: [
      { id: 'li-11', description: 'MVP Development (50h @ $120/hr)', quantity: 50, rate: 120, total: 6000 },
      { id: 'li-12', description: 'API Integration & Testing (25h @ $120/hr)', quantity: 25, rate: 120, total: 3000 },
      { id: 'li-13', description: 'Design & UI/UX (17h @ $100/hr)', quantity: 17, rate: 100, total: 1700 },
    ],
    subtotal: 10700,
    tax: 1070,
    total: 11770,
    dueDate: '2024-05-31',
    notes: 'Invoice for completed MVP development.',
    createdAt: '2024-04-15',
  },
]

export const mockProposals: Proposal[] = [
  {
    id: 'prop-1',
    clientId: 'client-3',
    clientName: 'Velocity Startups',
    title: 'Growth Marketing Strategy - Q3 Proposal',
    status: 'sent',
    lineItems: [
      { id: 'pli-1', description: 'Monthly Marketing Strategy & Planning', quantity: 1, rate: 2000, total: 2000 },
      { id: 'pli-2', description: 'Ad Campaign Management (3 months)', quantity: 3, rate: 1500, total: 4500 },
      { id: 'pli-3', description: 'Analytics & Reporting', quantity: 1, rate: 1000, total: 1000 },
    ],
    total: 7500,
    intro: 'Based on our discussion, here is a comprehensive proposal for Q3 growth marketing services.',
    terms: '50% deposit required upfront, balance due upon completion. Services to begin June 1, 2024.',
    sentAt: '2024-04-08',
    createdAt: '2024-04-05',
  },
  {
    id: 'prop-2',
    clientId: 'client-4',
    clientName: 'Collins & Co Law',
    title: 'Website & Legal Document Templates',
    status: 'draft',
    lineItems: [
      { id: 'pli-4', description: 'Professional Website Build', quantity: 1, rate: 4500, total: 4500 },
      { id: 'pli-5', description: 'Document Template Suite (5 templates)', quantity: 5, rate: 800, total: 4000 },
      { id: 'pli-6', description: 'SEO & Accessibility Audit', quantity: 1, rate: 1000, total: 1000 },
      { id: 'pli-7', description: 'Maintenance & Support (6 months)', quantity: 1, rate: 2500, total: 2500 },
    ],
    total: 12000,
    intro: 'Custom legal services website with integrated document templates.',
    terms: 'Full payment due before project start. Timeline: 8 weeks.',
    createdAt: '2024-03-20',
  },
  {
    id: 'prop-3',
    clientId: 'client-5',
    clientName: 'Reyes Creative Agency',
    title: 'Ongoing Creative Services Retainer',
    status: 'accepted',
    lineItems: [
      { id: 'pli-8', description: 'Monthly Retainer (40 hours)', quantity: 1, rate: 3600, total: 3600 },
      { id: 'pli-9', description: 'Rush Project Discount (20%)', quantity: 1, rate: -720, total: -720 },
    ],
    total: 2880,
    intro: 'Thank you for choosing us for your ongoing creative needs.',
    terms: 'Monthly retainer due on the 1st of each month. Includes 40 billable hours.',
    sentAt: '2024-03-01',
    createdAt: '2024-02-25',
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Complete logo concepts',
    description: 'Deliver 3 logo design concepts for client review',
    status: 'done',
    dueDate: '2024-04-10',
    createdAt: '2024-04-01',
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Design brand guidelines',
    description: 'Comprehensive brand guidelines document with colors, fonts, and usage',
    status: 'in_progress',
    dueDate: '2024-05-01',
    createdAt: '2024-04-05',
  },
  {
    id: 'task-3',
    projectId: 'proj-2',
    title: 'Content calendar for April',
    description: 'Social media content calendar for April',
    status: 'done',
    dueDate: '2024-04-05',
    createdAt: '2024-03-28',
  },
  {
    id: 'task-4',
    projectId: 'proj-2',
    title: 'Email template design',
    description: 'Design 4 email templates for campaign',
    status: 'in_progress',
    dueDate: '2024-04-20',
    createdAt: '2024-04-10',
  },
  {
    id: 'task-5',
    projectId: 'proj-3',
    title: 'Homepage design mockup',
    description: 'Create desktop and mobile mockups for homepage',
    status: 'done',
    dueDate: '2024-03-25',
    createdAt: '2024-03-15',
  },
  {
    id: 'task-6',
    projectId: 'proj-4',
    title: 'API integration testing',
    description: 'Test all third-party API integrations',
    status: 'in_progress',
    dueDate: '2024-04-25',
    createdAt: '2024-04-10',
  },
  {
    id: 'task-7',
    projectId: 'proj-5',
    title: 'Keyword research and analysis',
    description: 'Research target keywords and compile analysis',
    status: 'todo',
    dueDate: '2024-04-20',
    createdAt: '2024-04-01',
  },
  {
    id: 'task-8',
    projectId: 'proj-5',
    title: 'First blog post - publish',
    description: 'Write and publish first blog post on company blog',
    status: 'in_progress',
    dueDate: '2024-04-18',
    createdAt: '2024-04-08',
  },
  {
    id: 'task-9',
    projectId: 'proj-8',
    title: 'GA4 event tracking setup',
    description: 'Configure custom events in Google Analytics 4',
    status: 'todo',
    dueDate: '2024-04-25',
    createdAt: '2024-04-05',
  },
  {
    id: 'task-10',
    projectId: 'proj-8',
    title: 'Dashboard mockup design',
    description: 'Design analytics dashboard mockup for client approval',
    status: 'done',
    dueDate: '2024-04-10',
    createdAt: '2024-04-02',
  },
]

export const mockTimeEntries: TimeEntry[] = [
  {
    id: 'te-1',
    projectId: 'proj-1',
    projectTitle: 'Brand Identity Redesign',
    clientName: 'Bright Digital Co',
    description: 'Logo design - 3 concept variations',
    hours: 4.5,
    hourlyRate: 85,
    date: '2024-04-10',
    createdAt: '2024-04-10',
  },
  {
    id: 'te-2',
    projectId: 'proj-1',
    projectTitle: 'Brand Identity Redesign',
    clientName: 'Bright Digital Co',
    description: 'Brand colors & typography selection',
    hours: 3.5,
    hourlyRate: 85,
    date: '2024-04-11',
    createdAt: '2024-04-11',
  },
  {
    id: 'te-3',
    projectId: 'proj-2',
    projectTitle: 'Q2 Marketing Campaign',
    clientName: 'Bright Digital Co',
    description: 'Campaign strategy workshop with client',
    hours: 2,
    hourlyRate: 85,
    date: '2024-04-12',
    createdAt: '2024-04-12',
  },
  {
    id: 'te-4',
    projectId: 'proj-3',
    projectTitle: 'Website Redesign',
    clientName: 'Santos Architecture',
    description: 'Homepage design & layout',
    hours: 6,
    hourlyRate: 95,
    date: '2024-04-09',
    createdAt: '2024-04-09',
  },
  {
    id: 'te-5',
    projectId: 'proj-3',
    projectTitle: 'Website Redesign',
    clientName: 'Santos Architecture',
    description: 'Portfolio page design',
    hours: 4,
    hourlyRate: 95,
    date: '2024-04-10',
    createdAt: '2024-04-10',
  },
  {
    id: 'te-6',
    projectId: 'proj-5',
    projectTitle: 'Content Strategy & SEO',
    clientName: 'Velocity Startups',
    description: 'Keyword research',
    hours: 3,
    hourlyRate: 75,
    date: '2024-04-08',
    createdAt: '2024-04-08',
  },
  {
    id: 'te-7',
    projectId: 'proj-5',
    projectTitle: 'Content Strategy & SEO',
    clientName: 'Velocity Startups',
    description: 'Blog post writing & optimization',
    hours: 3.5,
    hourlyRate: 75,
    date: '2024-04-11',
    createdAt: '2024-04-11',
  },
  {
    id: 'te-8',
    projectId: 'proj-4',
    projectTitle: 'Mobile App MVP',
    clientName: 'Santos Architecture',
    description: 'API integration development',
    hours: 8,
    hourlyRate: 120,
    date: '2024-04-08',
    createdAt: '2024-04-08',
  },
  {
    id: 'te-9',
    projectId: 'proj-4',
    projectTitle: 'Mobile App MVP',
    clientName: 'Santos Architecture',
    description: 'Bug fixes and testing',
    hours: 5,
    hourlyRate: 120,
    date: '2024-04-10',
    createdAt: '2024-04-10',
  },
  {
    id: 'te-10',
    projectId: 'proj-2',
    projectTitle: 'Q2 Marketing Campaign',
    clientName: 'Bright Digital Co',
    description: 'Email template design',
    hours: 4,
    hourlyRate: 85,
    date: '2024-04-11',
    createdAt: '2024-04-11',
  },
  {
    id: 'te-11',
    projectId: 'proj-8',
    projectTitle: 'Analytics Dashboard',
    clientName: 'Bright Digital Co',
    description: 'GA4 setup and configuration',
    hours: 3,
    hourlyRate: 90,
    date: '2024-04-10',
    createdAt: '2024-04-10',
  },
  {
    id: 'te-12',
    projectId: 'proj-8',
    projectTitle: 'Analytics Dashboard',
    clientName: 'Bright Digital Co',
    description: 'Dashboard mockup design',
    hours: 2.5,
    hourlyRate: 90,
    date: '2024-04-11',
    createdAt: '2024-04-11',
  },
  {
    id: 'te-13',
    projectId: 'proj-1',
    projectTitle: 'Brand Identity Redesign',
    clientName: 'Bright Digital Co',
    description: 'Revision based on client feedback',
    hours: 2,
    hourlyRate: 85,
    date: '2024-04-12',
    createdAt: '2024-04-12',
  },
  {
    id: 'te-14',
    projectId: 'proj-3',
    projectTitle: 'Website Redesign',
    clientName: 'Santos Architecture',
    description: 'Interior pages & detail designs',
    hours: 5.5,
    hourlyRate: 95,
    date: '2024-04-11',
    createdAt: '2024-04-11',
  },
  {
    id: 'te-15',
    projectId: 'proj-5',
    projectTitle: 'Content Strategy & SEO',
    clientName: 'Velocity Startups',
    description: 'On-page SEO optimization',
    hours: 2.5,
    hourlyRate: 75,
    date: '2024-04-12',
    createdAt: '2024-04-12',
  },
]

export const mockConversations: Conversation[] = [
  {
    clientId: 'client-1',
    clientName: 'Alex Turner',
    clientCompany: 'Bright Digital Co',
    lastMessage: 'The new mockups look great! Just a few tweaks needed on the color palette.',
    lastMessageAt: '2024-04-12T14:30:00Z',
    unreadCount: 0,
    messages: [
      {
        id: 'msg-1',
        clientId: 'client-1',
        sender: 'client',
        body: 'Hi! Just checking in on the progress of the brand redesign. How are the logo concepts coming along?',
        createdAt: '2024-04-10T09:15:00Z',
      },
      {
        id: 'msg-2',
        clientId: 'client-1',
        sender: 'user',
        body: 'Great question! I have 3 logo concepts ready for review. I\'ll send them over by end of day tomorrow.',
        createdAt: '2024-04-10T10:45:00Z',
        readAt: '2024-04-10T10:46:00Z',
      },
      {
        id: 'msg-3',
        clientId: 'client-1',
        sender: 'client',
        body: 'Perfect! Looking forward to seeing them. Also, should we schedule a call to discuss the brand guidelines timeline?',
        createdAt: '2024-04-11T13:20:00Z',
      },
      {
        id: 'msg-4',
        clientId: 'client-1',
        sender: 'user',
        body: 'Absolutely. How about Thursday at 2 PM? I can do a quick screen share to walk through everything.',
        createdAt: '2024-04-11T14:00:00Z',
        readAt: '2024-04-11T14:05:00Z',
      },
      {
        id: 'msg-5',
        clientId: 'client-1',
        sender: 'client',
        body: 'The new mockups look great! Just a few tweaks needed on the color palette.',
        createdAt: '2024-04-12T14:30:00Z',
      },
    ],
  },
  {
    clientId: 'client-2',
    clientName: 'Maria Santos',
    clientCompany: 'Santos Architecture',
    lastMessage: 'Can we discuss the timeline for the mobile app MVP? Need to plan for client handoff.',
    lastMessageAt: '2024-04-11T16:45:00Z',
    unreadCount: 2,
    messages: [
      {
        id: 'msg-6',
        clientId: 'client-2',
        sender: 'client',
        body: 'The website design is looking amazing. The team is really impressed with the modern aesthetic.',
        createdAt: '2024-04-09T11:00:00Z',
      },
      {
        id: 'msg-7',
        clientId: 'client-2',
        sender: 'user',
        body: 'Thank you so much! I\'m thrilled the team loves it. I\'ll start development this week.',
        createdAt: '2024-04-09T14:30:00Z',
        readAt: '2024-04-09T14:35:00Z',
      },
      {
        id: 'msg-8',
        clientId: 'client-2',
        sender: 'client',
        body: 'Can we discuss the timeline for the mobile app MVP? Need to plan for client handoff.',
        createdAt: '2024-04-11T16:45:00Z',
      },
      {
        id: 'msg-9',
        clientId: 'client-2',
        sender: 'user',
        body: 'Of course! The MVP should be ready for testing by end of next week. Want to schedule a call tomorrow?',
        createdAt: '2024-04-11T17:15:00Z',
        readAt: '2024-04-11T17:20:00Z',
      },
    ],
  },
]
